/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function checkJwt(token: string): Promise<string>

export declare function checkPass(email: string, pass: string): Promise<boolean>

export declare function createUser(email: string, pass?: string | undefined | null, oauthProvider?: string | undefined | null): Promise<User>

export declare function deleteUser(email: string): Promise<User>

export declare function genJwt(uid: string, email: string): Promise<string>

export declare function initDbs(): Promise<void>

export declare function refreshJwt(token: string): Promise<string>

export declare function searchUsers(emailStr: string): Promise<Array<User>>
export interface User {
  uid: string
  email: string
  pwdHash?: string
  oauthProvider?: string
  createTime: number
}
