/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addUser(email: string, pass?: string | undefined | null, oauthProvider?: string | undefined | null): Promise<User>

export declare function connectDb(): Promise<string>

export declare function initializeDbs(): Promise<void>

export declare function searchUsers(emailStr: string): Promise<Array<User>>

export interface User {
  uid: string
  email: string
  pwdHash?: string
  oauthProvider?: string
  createTime: number
}
