/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function initializeDbs(): Promise<void>
export interface User {
  uid: string
  email: string
  pwdHash?: string
  oauthProvider?: string
  createTime: number
}
